HERE:	ORG 0000H			STARTING FROM 0000H
	MOV A, #38H			8-BIT MODE, USE 2 ROWS, 5*7 PIXEL DOTS
	ACALL CMND			38H TRANSFERRED TO LCD
	MOV A, #0FH			LCD ON, CURSOR ON, BLINKING ON
	ACALL CMND			0FH TRANSFERRED TO LCD
	MOV A, #06H			INCREMENT CURSOR
	ACALL CMND			06H TRANSFERRED TO LCD
	MOV A, #01H			CLEAR DISPLAY,  RETURN CURSOR TO HOME
	ACALL CMND			01H TRANSFERRED TO LCD
	MOV A, #80H			CURSOR AT LINE 1, POSITION 0
	ACALL CMND			80H TRANSFERRED TO LCD
	CLR A				ACC SET TO 0
	MOV R0, #0AH			USING R0 AS COUNTER
	MOV R1, #0DH			USING R1 AS COUNTER
	MOV DPTR, #300H			DPTR POINTS TO 300H AT 300H ASCII VALUES ARE STORED
LOOP1:	MOVC A, @A+DPTR			ACCESSING ASCII VALUES ONE BY ONE AND STORING TO ACC
	ACALL DISP			ASCII VALUES ARE TRANSFERRED TO LCD
	INC DPTR			INCREASING DPTR TO ACCESS ALL RECQUIRED LOCATION 
	CLR A				ACC SET TO 0
	DJNZ R0, LOOP1			IF COUNTER=0 GET OUT OF LOOP1
	MOV A, #0C0H			CURSOR LINE 2, POSITION 0
	ACALL CMND			C0H TRANSFERRED TO LCD
	CLR A				ACC SET TO 0
	MOV DPTR, #30AH			DPTR POINTS TO 30AH AT 30AH ASCII VALUES ARE STORED
LOOP2:	MOVC A, @A+DPTR			ACCESSING ASCII VALUES ONE BY ONE AND STORING TO ACC
	ACALL DISP			ASCII VALUES ARE TRANSFERRED TO LCD
	INC DPTR			INCREASING DPTR TO ACCESS ALL RECQUIRED LOCATION
	CLR A				ACC SET TO 0
	DJNZ R1, LOOP2			IF COUNTER=0 GET OUT OF LOOP2
	SJMP HERE			REPEAT THE SAME PROCESS AGAIN AND AGAIN
	ORG 300H	
	TABEL1: DB 43H,52H,45H,41H,54H,45H,44H,20H,42H,59H			ASCII VALUES FOR “CREATED BY”
	ORG 30AH	
	TABEL2: DB 47H,4FH,50H,41H,4CH,20H,41H,47H,41H,52H,57H,41H,4CH		ASCII VALUES FOR “GOPAL AGARWAL”
CMND:	MOV P1,A			P1 <= A
	CLR P3.5			COMMAND REGISTER ACTIVATED
	CLR P3.4			WRITE COMMAND ON LCD ACTIVATED
	SETB P3.3			LCD ENABLE SET TO 1 
	CLR P3.3			LCD ENABLE SET TO 0
	ACALL DELAY			TIME DELAY TO LET PRESENT TASK TO BE EXECUTED,  ELIMINATE THE NEED TO CHECK BUSY FLAG (BF)
	RET				RETURN
DISP:	MOV P1, A			P1 <= A
	SETB P3.5			DATA REGISTER ACTIVATED
	CLR P3.4			WRITE COMMAND ON LCD ACTIVATED
	SETB P3.3			LCD ENABLE SET TO 1
	CLR P3.3			LCD ENABLE SET TO 0
	ACALL DELAY			TIME DELAY TO LET PRESENT TASK TO BE EXECUTED,  ELIMINATE THE NEED TO CHECK BUSY FLAG (BF)
	RET				RETURN
DELAY: 	MOV R2, #08H			DELAY SUBROUTINE FOR 60   MICRO SECOND
DEL:	DJNZ R2, DEL	
	RET	
	END	
